apiVersion: v1
kind: Secret
metadata:
  name: iiitb-frontend-secret
type: Opaque
data:
  REACT_APP_FIREBASE_API_KEY: "QUl6YVN5QjF0OWRqV0ZtS0Q4b0FwcHEtbkVfejh5V1FJNmdEek8w"
  REACT_APP_FIREBASE_AUTH_DOMAIN: "aWlpdGItY29tbXVuaXR5LmZpcmViYXNlYXBwLmNvbQ=="
  REACT_APP_FIREBASE_PROJECT_ID: "aWlpdGItY29tbXVuaXR5"
  REACT_APP_FIREBASE_STORAGE_BUCKET: "aWlpdGItY29tbXVuaXR5LmFwcHNwb3QuY29t"
  REACT_APP_FIREBASE_MESSAGING_SENDER_ID: "NTgwODU5MjM3MTc3"
  REACT_APP_FIREBASE_APP_ID: "MTo1ODA4NTkyMzcxNzc6d2ViOmE1NjE1ZGJkYjcwYzBkMjQzMTBlZTg="
  REACT_APP_FIREBASE_MEASUREMENT_ID: "Ry03WENMRFNUU0U2"